# Generated by Django 4.1.3 on 2023-04-20 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='photo_article',
            field=models.ImageField(default=1, upload_to='photo'),
            preserve_default=False,
        ),
    ]
